<?php 
$base_scn_array[] = "prefix=000_ermanga00001,param=h%%%1girl,multiple boys,nipples,breasts,licking,2boys,hetero,realistic,bra,teeth,underwear,shirt,indoors,clenched teeth,clothes lift,tongue,white shirt,white bra,grabbing,holding another's wrist,shirt lift";
$base_scn_array[] = "prefix=001_ermanga00002%%%1girl,rope,solo,shibari,pantyhose,bdsm,school uniform,bound,bondage,smile,necktie,skirt,sweater,crotch rope";
$base_scn_array[] = "prefix=002_ermanga00003%%%1girl,pantyhose,solo,rope,bdsm,blush,mole under mouth,bondage,bound,mole,shibari,breasts,open mouth,panties under pantyhose,underwear";
$base_scn_array[] = "prefix=003_ermanga00004%%%1girl,multiple boys,hetero,penis,anal,multiple penises,nipples,2boys,group sex,nude,breasts,sex,threesome,mmf threesome,pussy,blush,medium breasts,spread legs,solo focus,completely nude,sweat";
$base_scn_array[] = "prefix=004_ermanga00005,param=h%%%1girl,solo,blush,tears,open mouth";
$base_scn_array[] = "prefix=005_ermanga00006%%%1girl,solo,school uniform,mole under mouth,mole,skirt,sketch,serafuku,looking at viewer,open mouth,pleated skirt,smile";
$base_scn_array[] = "prefix=006_ermanga00007%%%1girl,solo,school uniform,glasses,skirt,serafuku,wind,long skirt,wind lift,arms behind back,neckerchief,looking at viewer,pleated skirt";
$base_scn_array[] = "prefix=007_ermanga00008%%%1girl,glasses,solo,open mouth,breasts,formal,looking at viewer,shirt,suit,office lady,upper body,collared shirt";
$base_scn_array[] = "prefix=008_ermanga00009,param=h%%%1girl,hetero,1boy,sex,breasts,sex from behind,nipples,thighhighs,blush,nude,open mouth,doggystyle,bouncing breasts,sweat,ass,ass grab,lace-trimmed legwear,lace trim";
$base_scn_array[] = "prefix=009_ermanga00010%%%1girl,underwear,breasts,panties,solo,nipples,ass,small breasts,topless,blush,looking back,looking at viewer,thong,from behind,standing,underwear only,indoors";
$base_scn_array[] = "prefix=010_ermanga00011%%%1girl,multiple boys,hetero,cum,penis,phone,nipples,group sex,multiple penises,facial,breasts,nude,gangbang,completely nude,loli,2boys,cellphone,small breasts,grabbing,holding phone,breast grab,smartphone,on back,fingering,3boys,spread legs,cum in pussy,blush,open mouth,lying,pussy,solo focus,cum in mouth,rape,after sex,mmf threesome";
$base_scn_array[] = "prefix=011_ermanga00012%%%1girl,hetero,loli,underwear,panties,multiple boys,nipples,licking,2boys,panty pull,licking nipple,shirt lift,pussy,small breasts,breasts,pussy juice,fingering,glasses,blush";
$base_scn_array[] = "prefix=012_ermanga00013,param=h%%%1girl,hetero,multiple boys,penis,fellatio,oral,2boys,multiple penises,mmf threesome,group sex,loli,threesome,cum,bottomless,handjob,solo focus,nipples,flat chest";
$base_scn_array[] = "prefix=013_ermanga00014,param=h%%%1girl,hetero,sex,1boy,nipples,loli,solo focus,sex from behind,shirt lift,doggystyle,breasts,arm held back,sweat,clothes lift,small breasts,bottomless,blush";
$base_scn_array[] = "prefix=014_ermanga00015,param=h%%%1girl,hetero,penis,mmf threesome,cum,multiple boys,group sex,threesome,multiple penises,2boys,sex,fellatio,oral,spitroast,double penetration,vaginal,condom,solo focus,nipples,cum in pussy,tears,pussy,nude";
$base_scn_array[] = "prefix=015_ermanga00016,param=h%%%1girl,hetero,cum,penis,sex,multiple boys,vaginal,2boys,loli,group sex,solo focus,cum in pussy,multiple penises,mmf threesome,nipples,threesome,anus,pussy,flat chest,oral,ass";
$base_scn_array[] = "prefix=016_ermanga00017%%%1girl,pussy,nipples,loli,spread pussy,solo,pussy juice,bottomless,breasts,female masturbation,small breasts,shirt lift,masturbation,flat chest,blush";
